spring:
  application:
    name: eureka-server
    
server:
  port: 1110

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# spring:
#   application:
#     name: eureka-cluster
# 
# eureka:
#   server:
#     enable-self-preservation: false
#     eviction-interval-timer-in-ms: 4000
# 
# #监控相关        
# management: 
#   security: 
#     enabled: false
#   health:  
#     mail:  
#       enabled: false
# endpoints:
#   restart:
#     enabled: true
#   shutdown:
#     enabled: true
#   health:
#     sensitive: false
#     
# # security:
# #   path:
# #     permit: /**/*.js, /**/*.css, /**
# #     auth: /**/*.jsp
# #     
# # ---
# # spring:
# #   profiles: discovery1
# # server:
# #   port: 8761
# # eureka:
# #   instance:
# #     hostname: discovery1
# #   client:
# #     service-url:
# #       default-zone: http://discovery2:8762/eureka
# #       
# # ---
# # spring:
# #   profiles: discovery2
# # server:
# #   port: 8762
# # eureka:
# #   instance:
# #     hostname: discovery2
# #   client:
# #     service-url:
# #       default-zone: http://discovery1:8761/eureka