spring:
  application:
    name: scs-service-usermanagement
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    host: 10.11.63.209
    port: 8000
    password: GoldWind
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1110/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #注册服务默认心跳时间,默认是30秒，也就是每30秒会向Eureka Server发起Renew操作。
    leaseRenewalIntervalInSeconds: 10
    #服务失效时间。默认是90秒，也就是如果Eureka Server在90秒内没有接收到来自ServiceProvider的Renew操作，就会把Service Provider剔除。
    leaseExpirationDurationInSeconds: 20

server:
  port: 8088
  
feign:
  httpclient:
    enabled: true

jwt:
  header: www-Authorization
  secret: goldwindtgcw
  tokenHead: "Bearer "
  access_token: 
    expiration: 604800
  refresh_token: 
    expiration: 28800
  
sms:
  template:
    verificationCode: SMS_121215144 #验证码短信模板代码
    resetPassword: SMS_138064309 #重置密码短信模板代码
    selectTeam: SMS_139075065 #选定团队短信模板代码

management: 
  security: 
    enabled: false
  health:  
    mail:  
      enabled: false
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#datasource  
druid: 
  datasource:  
    name: era  
    url: jdbc:postgresql://10.11.63.233:5432/fyz_demo 
    username: fyz_demo  
    password: JzoY6zbz4Dp0bdhp  
    # 使用druid数据源  
    type: com.alibaba.druid.pool.DruidDataSource  
    driver-class-name: org.postgresql.Driver  
    # 下面为连接池的补充设置，应用到上面所有数据源中  
    # 初始化大小，最小，最大  
    initialSize: 5  
    minIdle: 5  
    maxActive: 20  
    # 配置获取连接等待超时的时间  
    maxWait: 60000  
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒  
    timeBetweenEvictionRunsMillis: 60000  
    # 配置一个连接在池中最小生存的时间，单位是毫秒  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false  
    # 打开PSCache，并且指定每个连接上PSCache的大小  
    poolPreparedStatements: true  
    maxPoolPreparedStatementPerConnectionSize: 20  
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  
    spring.datasource.filters: stat,wall,log4j  
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录  
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  
    # 合并多个DruidDataSource的监控数据  
    #useGlobalDataSourceStat: true 

# 默认mybatis配置      
mybatis:
  mapperLocations: classpath*:mapper/**/*Dao.xml
  executor-type: REUSE 
  configuration:
    map-underscore-to-camel-case: true    
    
# logging配置，本地默认使用debug级别
logging:
  level:
    org:
      mybatis: DEBUG 

    